### ISSUE TITLE
'PHashML' object has no attribute 'imghash'

### ISSUE THREAD

**Issue by devharsh** [starkdg/pyphashml#1]
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-7-7a0947d89fa5>](https://localhost:8080/#) in <module>()
----> 1 x = phashmlctx.imghash("plain.png")
      2 y = phashmlctx.imghash("stego.png")
      3 d = phashmlctx.hamming_distance(x, y)

AttributeError: 'PHashML' object has no attribute 'imghash'
```

**Comment by starkdg** [comment]
Hi devharsh,

Could you please include the steps you took to reproduce the problem? 

Is this your own program?   
There's a sample test program in tests directory.  

dgs

**Comment by devharsh** [comment]
https://colab.research.google.com/drive/1RhvIs1q_wmzA0imJNnW4gBOauR-sLOIb?usp=sharing

**Comment by starkdg** [comment]
Thanks.  I've reproduced the error on my machine.   FWIW, the protobuf has to go back to version 3.20.1.  But that's not the error, so not sure why its throwing this now.   Let me keep looking.

**Comment by devharsh** [comment]
please let me know if i can help in any way to solve it 🙃

Best,
Devharsh.

On Jul 17, 2022, at 1:13 PM, David Starkweather ***@***.***> wrote:

﻿

Thanks. I've reproduced the error on my machine. FWIW, the protobuf has to go back to version 3.20.1. But that's not the error, so not sure why its throwing this now. Let me keep looking.

**Comment by starkdg** [comment]
ok.   The name of the function was not updated on the readme.   Try the following. 

```
from pyphashml.phashml import phashmlctx
from pyphashml.phashml import phashml_distance

x = phashmlctx.image_hash("/path/to/file.jpg")
y = phashmlctx.image_hash("path/to/file2.jpg")

d = phashml_distance(x , y)
x
y
d
```
I just tried it, and that code works on my machine.   I changed the function name somewhere along the way, and forgot to update the docs.  My apologies.  

[ The code above was edited once for a typo.  Including this in case you tried it before the edit ].

**Comment by devharsh** [comment]
yup, that works 👍
