### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by query-wow** [starkdg/pyphashml#3]
Can't install this package using pip because it can't find a suitable tensorflow version.

`ERROR: Could not find a version that satisfies the requirement tensorflow<2,>=1.14 (from pyphashml) (from versions: 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3)
ERROR: No matching distribution found for tensorflow<2,>=1.14`

Using Python 3.10

**Comment by query-csharp** [comment]
Using python 3.7 fixes the issue
